name: NodeJS with vuepro

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout #检出
              uses: actions/checkout@main #检出的依赖2
              with:
                  persist-credentials: false #不保存证书
            - name: Cache Node Dependencies #设置依赖缓存
              id: cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{runner.os}}-npm-caches-${{ hashFiles('package-lock.json')}}
            - name: Install Dependencies #安装外层依赖
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                  npm install --force
            - name: build project
              run: |
                  npm run run build
            - name: deploy file to server 
              uses: wlixcc/SFTP-Deploy-Action@v1.0
              with:
                username: 'root'   #ssh user name
                SSH_PRIVATE_KEY: ${{secrets.ACCESS_TOKEN}}
                local_path: './dist/*'
                remote_path: '/data/webStatic/dist'
